apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: pomerium-tls
  issuerRef:
    name: pomerium-issuer
    kind: Issuer
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ .Release.Name }}-pomerium-proxy.default.svc.cluster.local
    - {{ .Release.Name }}-pomerium-authorize.default.svc.cluster.local
    - {{ .Release.Name }}-pomerium-databroker.default.svc.cluster.local
    - {{ .Release.Name }}-pomerium-authenticate.default.svc.cluster.local
    # TODO - If you're not using the Pomerium Ingress controller, you may want a wildcard entry as well.
    #- "*.localhost.pomerium.io" # Quotes are required to escape the wildcard
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-redis-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: pomerium-redis-tls
  issuerRef:
    name: pomerium-issuer
    kind: Issuer
  dnsNames:
    - {{ .Release.Name }}-redis-master.default.svc.cluster.local
    - {{ .Release.Name }}-redis-headless.default.svc.cluster.local
    - {{ .Release.Name }}-redis-replicas.default.svc.cluster.local
