apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: takemoto-ai-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: '*.takemoto.ai'
  secretName: takemoto-ai-cert
  dnsNames:
    - takemoto.ai
    - '*.takemoto.ai'
  issuerRef:
    name: cloudflare-letsencrypt-prod
    kind: Issuer