apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-letsencrypt
  namespace: default
spec:
  acme:
    # TODO: variable extract
    # TODO: change to prod
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: matt@takemoto.ai
    privateKeySecretRef:
      name: cloudflare-letsencrypt-pk
    solvers:
    - dns01:
        cloudflare:
          email: matt@takemoto.ai
          apiTokenSecretRef:
            name: cloudflare-credentials
            key: cloudflare-apiKey
      selector:
        dnsZones:
          - 'takemoto.ai'