# This is a SecretProviderClass example using system-assigned identity to access your key vault

# WARNING: All secrets in the spec.parameters.objects array MUST have a reference to the synced
# kubernetes "spec.secretObjects" array, otherwise an obscure "file name must not be empty" error gets thrown
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    tenantId: "66be6fbb-690d-4140-badf-30e376f34f5a" # The tenant ID of the key vault
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: "eff306e3-69a9-407f-9097-e220a059c998" # This is the applicationId, not principalId of the user-assigned identity
    keyvaultName: ohiakvprod
    cloudName: "AzurePublicCloud" # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: monica-app-key
          objectType: secret
        - |
          objectName: monica-db-username
          objectType: secret
        - |
          objectName: monica-db-pass
          objectType: secret
        - |
          objectName: cloudflare-apiKey
          objectType: secret
        - |
          objectName: cloudflare-email
          objectType: secret
        - |
          objectName: auth0-pomerium-clientId
          objectType: secret
        - |
          objectName: auth0-pomerium-clientSecret
          objectType: secret
  secretObjects:
  - secretName: monicasecrets
    data:
    - key: monica-app-key
      objectName: monica-app-key
    - key: monica-db-username
      objectName: monica-db-username
    - key: monica-db-pass
      objectName: monica-db-pass
    type: Opaque
  - secretName: cloudflare-credentials
    data:
    - key: apiKey
      objectName: cloudflare-apiKey
    - key: email
      objectName: cloudflare-email
    type: Opaque
  - secretName: auth0-pomerium-credentials
    data:
    - key: IDP_CLIENT_ID
      objectName: auth0-pomerium-clientId
    - key: IDP_CLIENT_SECRET
      objectName: auth0-pomerium-clientSecret
    type: Opaque
