kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline
  namespace: {{ .Release.Namespace }}
spec:
  containers:
    - name: busybox
      image: k8s.gcr.io/e2e-test-images/busybox:1.29-1
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
      env:
      - name: MONICA_DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: monicasecrets
            key: monica-db-username
      - name: MONICA_DB_PASS
        valueFrom:
          secretKeyRef:
            name: monicasecrets
            key: monica-db-pass
      - name: MONICA_APP_KEY
        valueFrom:
          secretKeyRef:
            name: monicasecrets
            key: monica-app-key
      - name: CF_API_Key
        valueFrom:
          secretKeyRef:
            name: cloudflare-credentials
            key: apiKey
      - name: CF_EMAIL
        valueFrom:
          secretKeyRef:
            name: cloudflare-credentials
            key: email
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-sync"
