apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monica
  annotations:
    cert-manager.io/issuer: cloudflare-letsencrypt-prod
    ingress.pomerium.io/policy: '[{"allow":{"or":[{"email":{"is":"matt@takemoto.ai"}}]}}]'
spec:
  ingressClassName: pomerium
  rules:
  - host: monica.takemoto.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-monica
            port:
              number: 80
  tls:
    - hosts:
        - monica.takemoto.ai
      secretName: takemoto-ai-cert