# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

monica:
  env:
    - name: APP_URL
      value: "https://monica.takemoto.ai"
    - name: APP_ENV
      value: "production" # force HTTPS
    - name: APP_TRUSTED_PROXIES
      value: "*"
    - name: APP_FORCE_URL
      value: true
    - name: DB_CONNECTION
      value: "mysql"
    - name: DB_HOST
      value: "ohiamttsql.mysql.database.azure.com"
    - name: DB_DATABASE
      value: "monica"
    - name: APP_DEBUG
      value: "true"
    - name: APP_KEY
      valueFrom:
        secretKeyRef:
          key: monica-app-key
          name: monicasecrets
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          key: monica-db-username
          name: monicasecrets
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: monica-db-pass
          name: monicasecrets
  ingress:
    main:
      enabled: true
      pathType: Prefix
      hosts:
        - host: monica.takemoto.ai
          paths:
            - path: /
              service:
  persistence:
    config:
      enabled: true
      mountPath: /var/www/html/storage

whoami:
  ingress:
    enabled: true
    pathType: Prefix
    hosts:
      - host: whoami.takemoto.ai
        paths:
          - /

pomerium:
  config:
    rootDomain: takemoto.ai
    generateTLS: true
    autocert: true
    autocert_ca:
  authenticate:
    idp:
      provider: auth0
      clientID: ""
      clientSecret: ""
      url: ""

kubernetes-dashboard:
  resources:
    limits:
      cpu: "200m"
