# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Monica
monica:
  env:
    - name: APP_URL
      value: "https://monica.takemoto.ai"
    - name: APP_ENV
      value: "production" # force HTTPS
    - name: APP_TRUSTED_PROXIES
      value: "*"
    - name: APP_FORCE_URL
      value: true
    - name: DB_CONNECTION
      value: "mysql"
    - name: DB_HOST
      value: "ohiamttsql.mysql.database.azure.com"
    - name: DB_DATABASE
      value: "monica"
    - name: APP_DEBUG
      value: "true"
    - name: APP_KEY
      valueFrom:
        secretKeyRef:
          key: monica-app-key
          name: monicasecrets
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          key: monica-db-username
          name: monicasecrets
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: monica-db-pass
          name: monicasecrets
  persistence:
    config:
      enabled: true
      mountPath: /var/www/html/storage

## Cert-manager
cert-manager:
  installCRDs: false

## Pomerium
pomerium:
  extraEnvFrom:
  - secretRef:
      name: auth0-pomerium-credentials

  authenticate:
    existingTLSSecret: pomerium-tls
    ingress:
      annotations:
        cert-manager.io/issuer: cloudflare-letsencrypt-prod
      tls:
        secretName: takemoto-ai-cert
    idp:
      provider: "auth0"
      url: "https://takemoto.us.auth0.com"

  proxy:
    existingTLSSecret: pomerium-tls

  databroker:
    existingTLSSecret: pomerium-tls
    storage:
      connectionString: "rediss://ape-mars-redis-master.default.svc.cluster.local"
      type: redis
      clientTLS:
        existingSecretName: pomerium-redis-tls
        existingCASecretKey: ca.crt

  authorize:
    existingTLSSecret: pomerium-tls

  redis:
    enabled: true
    auth:
      enabled: false
    usePassword: false
    generateTLS: false
    tls:
      certificateSecret: pomerium-redis-tls

  ingressController:
    enabled: true

  ingress:
    enabled: false

  config:
    rootDomain: takemoto.ai
    existingCASecret: pomerium-tls
    generateTLS: false # On by default, disabled when cert-manager or another solution is in place.
    generateSigningKey: true
    forceGenerateSigningKey: false

## Kube dashboard
kubernetes-dashboard:
  resources:
    limits:
      cpu: "200m"
